[pytest]

addopts = --alluredir=reports/allure-results --allure-no-capture
norecursedirs = .venv
markers =
    p0: 冒烟测试（核心流程，失败则阻断发布）
    p1: 重要功能（常规回归必测）
    p2: 边缘场景（异常分支、边界值）
    smoke: 冒烟标签
    single: 单接口测试
    multiple: 多步骤场景/集成测试
    negative: 异常/负面测试用例
